#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

cp 0/alpha.water.orig 0/alpha.water
cp 0/C.orig 0/C

runApplication blockMesh
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
